import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { requirePermission } from '@/lib/permissions/session';
import { loadStudentReports } from '@/lib/reports/student-reports';

export async function GET(request: Request) {
  const session = await requirePermission('download_reports');
  const url = new URL(request.url);
  const classId = url.searchParams.get('class_id') || undefined;
  const examinationId = url.searchParams.get('examination_id') || undefined;
  const data = await loadStudentReports(session.school!.id, classId, examinationId);
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  for (const student of data.students as any[]) {
    const page = pdf.addPage([595, 842]);
    let y = 800;
    const draw = (text: string, size = 10, isBold = false) => {
      page.drawText(text.slice(0, 105), { x: 42, y, size, font: isBold ? bold : font, color: rgb(0.08, 0.12, 0.16) });
      y -= size + 6;
    };
    draw(data.school?.name ?? 'School', 17, true);
    draw([data.school?.address, data.school?.region, data.school?.district].filter(Boolean).join(', '), 9);
    draw([data.school?.phone, data.school?.email].filter(Boolean).join(' · '), 9);
    draw(data.school?.motto ?? '', 9);
    y -= 8;
    draw('STUDENT REPORT CARD', 13, true);
    draw(`${student.admission_number} · ${student.first_name} ${student.last_name}`, 11, true);
    draw(`Class: ${student.classes?.name ?? 'Unassigned'}${student.guardian_name ? ` · Guardian: ${student.guardian_name}` : ''}`);
    y -= 8;
    page.drawLine({ start: { x: 42, y }, end: { x: 553, y }, thickness: 1, color: rgb(0.7, 0.7, 0.7) });
    y -= 18;
    const summaries = (data.results as any[]).filter((result) => result.student_id === student.id);
    for (const summary of summaries) {
      draw(`${summary.examinations?.name ?? 'Examination'} (${summary.examinations?.term ?? ''})`, 10, true);
      draw('Subject                         Mark   Grade   Point   Remark', 9, true);
      const studentMarks = (data.marks as any[]).filter((mark) => mark.student_id === student.id && mark.examination_id === summary.examination_id);
      for (const mark of studentMarks) {
        draw(`${String(mark.subjects?.name ?? '').padEnd(30)} ${String(mark.score ?? '—').padStart(4)}   ${String(mark.grade ?? '—').padEnd(6)} ${String(mark.points ?? '—').padStart(5)}   ${mark.remark ?? ''}`, 9);
        if (y < 120) break;
      }
      draw(`Total: ${summary.total_marks ?? '—'} · Average: ${summary.average_mark ?? '—'} · Points: ${summary.aggregate ?? '—'}`, 9);
      draw(`Division: ${summary.division ?? '—'} · Position: ${summary.position ?? '—'} · Status: ${summary.overall_status ?? summary.status ?? '—'}`, 9);
      y -= 6;
    }
    draw('Generated by ElimuDira', 8);
  }

  if (!data.students.length) {
    const page = pdf.addPage([595, 842]);
    page.drawText('No student reports are available for this class.', { x: 42, y: 780, size: 12, font });
  }

  const bytes = await pdf.save();
  const className = (data.classes as any[]).find((item) => item.id === classId)?.name ?? 'all-classes';
  return new Response(Buffer.from(bytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${className.replace(/[^a-z0-9-_]+/gi, '-')}-reports.pdf"`,
      'Cache-Control': 'private, no-store',
    },
  });
}
