import { requirePermission } from '@/lib/permissions/session';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { Card, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label, Select } from '@/components/ui/field';
import { ActionForm } from '@/components/ui/action-form';
import { createExam, processExamination, recalculateExamination } from '@/lib/actions/exams';
import Link from 'next/link';

export default async function ExamsPage() {
  const session = await requirePermission('view_exams'); const supabase = await createServerSupabaseClient();
  const [{ data: exams }, { data: types }] = await Promise.all([supabase.from('examinations').select('id,name,term,status,starts_on,ends_on,examination_type_id').eq('school_id', session.school!.id).order('created_at', { ascending: false }), supabase.from('examination_types').select('id,name').eq('school_id', session.school!.id).order('name')]);
  return <div className="space-y-6"><div className="flex items-end justify-between border-b border-border pb-5"><div><h2 className="text-2xl font-semibold text-ink">Examinations</h2><p className="help-text mt-1">Create assessment periods and manage their marks and results.</p></div><Link href="/dashboard/exams/marks" className="rounded-md bg-brand px-4 py-2 text-sm font-medium text-white">Enter marks</Link></div><Card><CardHeader><CardTitle>Create examination</CardTitle></CardHeader><ActionForm action={createExam} submitLabel="Create examination"><div className="grid grid-cols-2 gap-4"><div><Label htmlFor="name">Name</Label><Input id="name" name="name" placeholder="Midterm Assessment" required /></div><div><Label htmlFor="term">Term</Label><Input id="term" name="term" placeholder="Term 1" required /></div><div><Label htmlFor="examination_type_id">Examination type</Label><Select id="examination_type_id" name="examination_type_id"><option value="">Use standard configuration</option>{(types ?? []).map((type: any) => <option key={type.id} value={type.id}>{type.name}</option>)}</Select></div><div><Label htmlFor="starts_on">Starts</Label><Input id="starts_on" name="starts_on" type="date" /></div><div><Label htmlFor="ends_on">Ends</Label><Input id="ends_on" name="ends_on" type="date" /></div></div></ActionForm></Card><Card><CardHeader><CardTitle>Examination register ({exams?.length ?? 0})</CardTitle></CardHeader><div className="space-y-2">{(exams ?? []).map((exam: any) => <div key={exam.id} className="flex items-center justify-between border-b border-line py-3 text-sm"><div><p className="font-medium">{exam.name}</p><p className="help-text">{exam.term} {exam.starts_on ? `· ${exam.starts_on}` : ''}</p></div><div className="flex items-center gap-3"><span className="capitalize text-muted">{exam.status}</span><ActionForm action={processExamination} submitLabel="Process"><input type="hidden" name="examination_id" value={exam.id} /></ActionForm><ActionForm action={recalculateExamination} submitLabel="Recalculate"><input type="hidden" name="examination_id" value={exam.id} /><input type="hidden" name="confirm" value="true" /></ActionForm></div></div>)}{(exams ?? []).length === 0 && <p className="help-text">Create the first examination above.</p>}</div></Card></div>;
}
