import { requireAnyPermission } from '@/lib/permissions/session';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { Card, CardHeader, CardTitle } from '@/components/ui/card';
import { ActionForm } from '@/components/ui/action-form';
import { Input } from '@/components/ui/input';
import { Label, Select } from '@/components/ui/field';
import { carryForwardPreviousYearBalance, createStudentCharge, requestFinanceAdjustment, requestPaymentReversal, reviewFinanceAdjustmentForm as reviewFinanceAdjustment } from '@/lib/actions/finance-ledger';

const money = (amount: number) => new Intl.NumberFormat('en-TZ', { style: 'currency', currency: 'TZS', maximumFractionDigits: 2 }).format(amount);
type SearchParams = { academic_year_id?: string; class_id?: string; enrollment_page?: string };

export default async function FinanceChargesPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const session = await requireAnyPermission(['view_finance', 'create_student_charges', 'manage_finance_adjustments', 'approve_finance_corrections']);
  const params = await searchParams;
  const supabase = await createServerSupabaseClient();
  const schoolId = session.school!.id;
  const [{ data: years }, { data: categories }, { data: classes }] = await Promise.all([
    supabase.from('academic_years').select('id, name, is_current').eq('school_id', schoolId).order('start_date', { ascending: false }),
    supabase.from('finance_fee_categories').select('id, name').eq('school_id', schoolId).eq('active', true).order('name'),
    supabase.from('classes').select('id, name').eq('school_id', schoolId).order('order_index'),
  ]);
  const academicYearId = params.academic_year_id ?? years?.find((year) => year.is_current)?.id ?? years?.[0]?.id ?? '';
  const enrollmentPage = Math.max(Number(params.enrollment_page) || 1, 1);
  let enrollmentQuery = supabase.from('student_enrollments').select('id, student_id, class_id, students!inner(admission_number, first_name, last_name), classes(name)', { count: 'exact' }).eq('school_id', schoolId).eq('academic_year_id', academicYearId).eq('status', 'active');
  if (params.class_id) enrollmentQuery = enrollmentQuery.eq('class_id', params.class_id);
  const [{ data: enrollments, count: enrollmentCount }, { data: charges }, { data: pendingAdjustments }, { data: payments }] = await Promise.all([
    enrollmentQuery.order('placed_at').range((enrollmentPage - 1) * 50, enrollmentPage * 50 - 1),
    supabase.from('fee_assessments').select('id, student_id, description, amount, due_date, created_at, students!inner(admission_number, first_name, last_name), student_enrollments(classes(name)), finance_fee_categories(name)').eq('school_id', schoolId).eq('academic_year_id', academicYearId).eq('legacy_year_unassigned', false).order('created_at', { ascending: false }).limit(50),
    session.permissions.has('approve_finance_corrections') ? supabase.from('finance_adjustments').select('id, student_id, adjustment_type, amount, reason, created_at, students!inner(admission_number, first_name, last_name)').eq('school_id', schoolId).eq('academic_year_id', academicYearId).eq('status', 'pending').order('created_at').limit(50) : Promise.resolve({ data: [] }),
    session.permissions.has('manage_finance_adjustments') ? supabase.from('fee_payments').select('id, receipt_number, student_id, amount, payment_date, students!inner(admission_number, first_name, last_name)').eq('school_id', schoolId).eq('academic_year_id', academicYearId).eq('legacy_year_unassigned', false).neq('status', 'reversed').order('payment_date', { ascending: false }).limit(50) : Promise.resolve({ data: [] }),
  ]);
  const canCreateCharge = session.permissions.has('create_student_charges');
  const canAdjust = session.permissions.has('manage_finance_adjustments');
  const enrollmentPages = Math.max(1, Math.ceil((enrollmentCount ?? 0) / 50));
  const enrollmentPageHref = (nextPage: number) => {
    const search = new URLSearchParams({ academic_year_id: academicYearId, enrollment_page: String(nextPage) });
    if (params.class_id) search.set('class_id', params.class_id);
    return `?${search.toString()}`;
  };

  return (
    <div className="space-y-6">
      <header className="flex flex-wrap items-end justify-between gap-4 border-b border-border pb-5"><div><p className="text-sm font-medium uppercase text-brand">Finance</p><h2 className="mt-1 text-xl font-semibold text-ink">Student charges</h2><p className="help-text mt-1">Charges are attached to the student&apos;s enrollment and academic year. Adjustments never overwrite the original charge.</p></div><form method="get" className="flex items-end gap-2"><div><Label htmlFor="academic_year_id">Academic year</Label><Select id="academic_year_id" name="academic_year_id" defaultValue={academicYearId}><option value="">Choose year</option>{(years ?? []).map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</Select></div><button className="h-10 rounded-md border border-border px-3 text-sm" type="submit">View</button></form></header>

      {canCreateCharge && <Card><CardHeader><CardTitle>Additional charge</CardTitle></CardHeader><p className="help-text mb-4">Use this for authorized charges not already included in a fee structure.</p><form method="get" className="mb-4 flex items-end gap-3"><input type="hidden" name="academic_year_id" value={academicYearId} /><div className="max-w-sm flex-1"><Label htmlFor="charge_class_id">Filter students by class</Label><Select id="charge_class_id" name="class_id" defaultValue={params.class_id ?? ''}><option value="">All classes</option>{(classes ?? []).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></div><button type="submit" className="h-10 rounded-md border border-border px-4 text-sm">Filter</button></form><ActionForm action={createStudentCharge} submitLabel="Create charge" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><Label htmlFor="enrollment_id">Student enrollment · {enrollmentCount ?? 0} matches</Label><Select id="enrollment_id" name="enrollment_id" defaultValue="" required><option value="" disabled>Choose student</option>{(enrollments ?? []).map((enrollment) => { const student = Array.isArray(enrollment.students) ? enrollment.students[0] : enrollment.students; const schoolClass = Array.isArray(enrollment.classes) ? enrollment.classes[0] : enrollment.classes; return <option key={enrollment.id} value={enrollment.id}>{student?.admission_number} · {student?.first_name} {student?.last_name} · {schoolClass?.name ?? 'No class'}</option>; })}</Select><div className="mt-2 flex gap-2 text-xs">{enrollmentPage > 1 && <a className="text-brand-dark hover:underline" href={enrollmentPageHref(enrollmentPage - 1)}>Previous 50</a>}{enrollmentPage < enrollmentPages && <a className="text-brand-dark hover:underline" href={enrollmentPageHref(enrollmentPage + 1)}>Next 50</a>}</div></div><div><Label htmlFor="fee_category_id">Category</Label><Select id="fee_category_id" name="fee_category_id" defaultValue="" required><option value="" disabled>Choose category</option>{(categories ?? []).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</Select></div><div><Label htmlFor="description">Description</Label><Input id="description" name="description" required maxLength={160} /></div><div><Label htmlFor="amount">Amount (TZS)</Label><Input id="amount" name="amount" type="number" min="0.01" step="0.01" required /></div><div><Label htmlFor="due_date">Due date</Label><Input id="due_date" name="due_date" type="date" /></div></ActionForm></Card>}

      {canAdjust && <Card><CardHeader><CardTitle>Carry forward previous-year balance</CardTitle></CardHeader><p className="help-text mb-4">Creates a clearly labelled charge for this year. The original year&apos;s balance and statement remain unchanged; each prior year can be carried forward once.</p><ActionForm action={carryForwardPreviousYearBalance} submitLabel="Carry forward balance" className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="carry_enrollment_id">Current enrollment</Label><Select id="carry_enrollment_id" name="enrollment_id" defaultValue="" required><option value="" disabled>Choose student enrollment</option>{(enrollments ?? []).map((enrollment) => { const student = Array.isArray(enrollment.students) ? enrollment.students[0] : enrollment.students; const schoolClass = Array.isArray(enrollment.classes) ? enrollment.classes[0] : enrollment.classes; return <option key={enrollment.id} value={enrollment.id}>{student?.admission_number} · {student?.first_name} {student?.last_name} · {schoolClass?.name ?? 'No class'}</option>; })}</Select></div><div><Label htmlFor="source_academic_year_id">Outstanding from academic year</Label><Select id="source_academic_year_id" name="source_academic_year_id" defaultValue="" required><option value="" disabled>Choose earlier year</option>{(years ?? []).filter((year) => year.id !== academicYearId).map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</Select></div><p className="help-text sm:col-span-2">Student choices are paginated above; filter by class before selecting from a large school.</p></ActionForm></Card>}

      {canAdjust && <Card><CardHeader><CardTitle>Request discount or adjustment</CardTitle></CardHeader><p className="help-text mb-4">Requests remain pending and do not affect balances until an authorized approver approves them.</p><ActionForm action={requestFinanceAdjustment} submitLabel="Submit for approval" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><Label htmlFor="assessment_id">Charge</Label><Select id="assessment_id" name="assessment_id" defaultValue="" required><option value="" disabled>Choose charge</option>{(charges ?? []).map((charge) => { const student = Array.isArray(charge.students) ? charge.students[0] : charge.students; return <option key={charge.id} value={charge.id}>{student?.admission_number} · {charge.description} · {money(Number(charge.amount))}</option>; })}</Select></div><div><Label htmlFor="adjustment_type">Type</Label><Select id="adjustment_type" name="adjustment_type" defaultValue="discount"><option value="discount">Discount</option><option value="waiver">Scholarship / waiver</option><option value="additional_charge">Additional charge</option><option value="correction">Correction</option></Select></div><div><Label htmlFor="direction">Correction direction</Label><Select id="direction" name="direction" defaultValue="debit"><option value="debit">Increase amount due</option><option value="credit">Reduce amount due</option></Select></div><div><Label htmlFor="adjustment_amount">Amount (TZS)</Label><Input id="adjustment_amount" name="amount" type="number" min="0.01" step="0.01" required /></div><div className="sm:col-span-2"><Label htmlFor="reason">Reason</Label><Input id="reason" name="reason" minLength={5} maxLength={300} required /></div></ActionForm></Card>}

      {session.permissions.has('approve_finance_corrections') && <Card><CardHeader><CardTitle>Pending adjustments ({pendingAdjustments?.length ?? 0})</CardTitle></CardHeader><div className="divide-y divide-line">{(pendingAdjustments ?? []).map((adjustment: any) => { const student = Array.isArray(adjustment.students) ? adjustment.students[0] : adjustment.students; return <div key={adjustment.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium text-ink">{student?.admission_number} · {adjustment.adjustment_type.replaceAll('_', ' ')} · {money(Number(adjustment.amount))}</p><p className="help-text">{adjustment.reason} · {adjustment.created_at.slice(0, 10)}</p></div><form action={reviewFinanceAdjustment} className="flex gap-2"><input type="hidden" name="adjustment_id" value={adjustment.id} /><button name="decision" value="approved" className="rounded-md bg-brand px-3 py-2 text-sm font-medium text-white">Approve</button><button name="decision" value="rejected" className="rounded-md border border-border px-3 py-2 text-sm">Reject</button></form></div>; })}{!pendingAdjustments?.length && <p className="help-text py-4">No adjustments awaiting approval.</p>}</div></Card>}

      {canAdjust && <Card><CardHeader><CardTitle>Request payment reversal</CardTitle></CardHeader><p className="help-text mb-4">Reversals are allocated back to the receipt&apos;s original charges and require approval.</p><ActionForm action={requestPaymentReversal} submitLabel="Submit reversal for approval" className="grid gap-4 sm:grid-cols-3"><div><Label htmlFor="reversal_payment_id">Receipt</Label><Select id="reversal_payment_id" name="payment_id" defaultValue="" required><option value="" disabled>Choose payment</option>{(payments ?? []).map((payment: any) => { const student = Array.isArray(payment.students) ? payment.students[0] : payment.students; return <option key={payment.id} value={payment.id}>{payment.receipt_number} · {student?.admission_number} · {money(Number(payment.amount))}</option>; })}</Select></div><div><Label htmlFor="reversal_amount">Reversal amount (TZS)</Label><Input id="reversal_amount" name="amount" type="number" min="0.01" step="0.01" required /></div><div><Label htmlFor="reversal_reason">Reason</Label><Input id="reversal_reason" name="reason" minLength={5} maxLength={300} required /></div></ActionForm></Card>}

      <Card><CardHeader><CardTitle>Recent charges</CardTitle></CardHeader><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border text-muted"><th className="px-3 py-2">Student</th><th className="px-3 py-2">Class</th><th className="px-3 py-2">Category</th><th className="px-3 py-2">Description</th><th className="px-3 py-2">Due</th><th className="px-3 py-2">Charge</th></tr></thead><tbody>{(charges ?? []).map((charge: any) => { const student = Array.isArray(charge.students) ? charge.students[0] : charge.students; const enrollment = Array.isArray(charge.student_enrollments) ? charge.student_enrollments[0] : charge.student_enrollments; const schoolClass = Array.isArray(enrollment?.classes) ? enrollment.classes[0] : enrollment?.classes; const category = Array.isArray(charge.finance_fee_categories) ? charge.finance_fee_categories[0] : charge.finance_fee_categories; return <tr key={charge.id} className="border-b border-line"><td className="px-3 py-3">{student?.admission_number} · {student?.first_name} {student?.last_name}</td><td className="px-3 py-3">{schoolClass?.name ?? '—'}</td><td className="px-3 py-3">{category?.name ?? '—'}</td><td className="px-3 py-3">{charge.description}</td><td className="px-3 py-3">{charge.due_date ?? '—'}</td><td className="px-3 py-3 font-semibold">{money(Number(charge.amount))}</td></tr>; })}</tbody></table></div>{!charges?.length && <p className="help-text p-4">No charges are recorded for this year yet.</p>}</Card>
    </div>
  );
}