'use client';

import { useState } from 'react';
import { ActionForm } from '@/components/ui/action-form';
import { Input } from '@/components/ui/input';
import { Select, Textarea } from '@/components/ui/field';
import { createFeeAssessment, createFeeStructure, recordPayment } from '@/lib/actions/finance';

type ClassOption = { id: string; name: string };
type StudentOption = { id: string; class_id: string | null; admission_number: string; first_name: string; last_name: string };
type YearOption = { id: string; name: string; is_current: boolean };
type StructureOption = { id: string; class_id: string | null; name: string; amount: number; due_date: string | null };
type AssessmentOption = { id: string; student_id: string; class_id: string | null; description: string; amount: number; paid: number; studentName: string };

const money = (value: number) => new Intl.NumberFormat('en-TZ', { style: 'currency', currency: 'TZS', maximumFractionDigits: 0 }).format(value);

export function FinanceEntryForms({ classes, students, years, structures, assessments }: { classes: ClassOption[]; students: StudentOption[]; years: YearOption[]; structures: StructureOption[]; assessments: AssessmentOption[] }) {
  const [assessmentClass, setAssessmentClass] = useState('');
  const [paymentClass, setPaymentClass] = useState('');
  const [paymentStudent, setPaymentStudent] = useState('');
  const assessmentStudents = students.filter((student) => !assessmentClass || student.class_id === assessmentClass);
  const paymentStudents = students.filter((student) => student.class_id === paymentClass);
  const paymentAssessments = assessments.filter((assessment) => assessment.class_id === paymentClass && assessment.student_id === paymentStudent && assessment.amount - assessment.paid > 0.005);

  return <div className="grid gap-6 lg:grid-cols-3">
    <ActionForm action={createFeeStructure} submitLabel="Create structure" className="space-y-4"><h3 className="text-base font-semibold text-ink">Fee structure</h3><p className="help-text">Define a reusable charge for a class or the whole school.</p><div><label className="label-text" htmlFor="structure_class_id">Class</label><Select id="structure_class_id" name="class_id"><option value="">All classes</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></div><div><label className="label-text" htmlFor="structure_year_id">Academic year</label><Select id="structure_year_id" name="academic_year_id"><option value="">Not specified</option>{years.map((year) => <option key={year.id} value={year.id}>{year.name}{year.is_current ? ' (current)' : ''}</option>)}</Select></div><div><label className="label-text" htmlFor="structure_name">What is being paid for</label><Input id="structure_name" name="name" placeholder="Tuition, transport, uniform..." required /></div><div><label className="label-text" htmlFor="structure_amount">Amount (TZS)</label><Input id="structure_amount" name="amount" type="number" min="1" step="0.01" required /></div><div><label className="label-text" htmlFor="structure_due_date">Due date</label><Input id="structure_due_date" name="due_date" type="date" /></div></ActionForm>
    <ActionForm action={createFeeAssessment} submitLabel="Create assessment" className="space-y-4"><h3 className="text-base font-semibold text-ink">Assess a student</h3><p className="help-text">Select a class and student, then apply a structure or enter a custom charge.</p><div><label className="label-text" htmlFor="assessment_class_id">Class</label><Select id="assessment_class_id" name="class_id" value={assessmentClass} onChange={(event) => setAssessmentClass(event.target.value)} required><option value="">Choose a class</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></div><div><label className="label-text" htmlFor="assessment_student_id">Student</label><Select id="assessment_student_id" name="student_id" required><option value="">Choose a student</option>{assessmentStudents.map((student) => <option key={student.id} value={student.id}>{student.admission_number} · {student.first_name} {student.last_name}</option>)}</Select></div><div><label className="label-text" htmlFor="fee_structure_id">Fee structure</label><Select id="fee_structure_id" name="fee_structure_id"><option value="">Custom fee below</option>{structures.filter((item) => !item.class_id || item.class_id === assessmentClass).map((item) => <option key={item.id} value={item.id}>{item.name} · {money(Number(item.amount))}</option>)}</Select></div><div><label className="label-text" htmlFor="assessment_description">Custom description</label><Input id="assessment_description" name="description" placeholder="Used when no structure is selected" required /></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="label-text" htmlFor="assessment_amount">Custom amount</label><Input id="assessment_amount" name="amount" type="number" min="1" step="0.01" required /></div><div><label className="label-text" htmlFor="assessment_due_date">Due date</label><Input id="assessment_due_date" name="due_date" type="date" /></div></div><Select id="assessment_year_id" name="academic_year_id" className="hidden"><option value="">Not specified</option></Select></ActionForm>
    <ActionForm action={recordPayment} submitLabel="Record payment" className="space-y-4"><h3 className="text-base font-semibold text-ink">Record payment</h3><p className="help-text">Choose the class and student before selecting an outstanding fee.</p><div><label className="label-text" htmlFor="payment_class_id">Class</label><Select id="payment_class_id" name="class_id" value={paymentClass} onChange={(event) => { setPaymentClass(event.target.value); setPaymentStudent(''); }} required><option value="">Choose a class</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></div><div><label className="label-text" htmlFor="payment_student_id">Student</label><Select id="payment_student_id" name="student_id" value={paymentStudent} onChange={(event) => setPaymentStudent(event.target.value)} required><option value="">Choose a student</option>{paymentStudents.map((student) => <option key={student.id} value={student.id}>{student.admission_number} · {student.first_name} {student.last_name}</option>)}</Select></div><div><label className="label-text" htmlFor="payment_assessment_id">Outstanding fee</label><Select id="payment_assessment_id" name="assessment_id" required><option value="">Choose a fee</option>{paymentAssessments.map((item) => <option key={item.id} value={item.id}>{item.description} · {money(Number(item.amount) - item.paid)} due</option>)}</Select></div><div><label className="label-text" htmlFor="payment_amount">Amount (TZS)</label><Input id="payment_amount" name="amount" type="number" min="1" step="0.01" required /></div><div><label className="label-text" htmlFor="payment_date">Payment date</label><Input id="payment_date" name="payment_date" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></div><div><label className="label-text" htmlFor="payment_method">Method</label><Select id="payment_method" name="method"><option value="cash">Cash</option><option value="mobile_money">Mobile money</option><option value="bank">Bank</option><option value="card">Card</option><option value="other">Other</option></Select></div><div><label className="label-text" htmlFor="payment_reference">Reference</label><Input id="payment_reference" name="reference" placeholder="Receipt or transaction number" /></div><Textarea id="payment_notes" name="notes" placeholder="Optional note" /></ActionForm>
  </div>;
}
