import { requirePermission } from '@/lib/permissions/session';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { Card, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/field';
import { ActionForm } from '@/components/ui/action-form';
import { acceptSchoolTransfer, cancelSchoolTransfer, promoteStudent, rejectSchoolTransfer, requestSchoolTransfer, transferStudentWithinSchool } from '@/lib/actions/transfers';

export default async function StudentTransfersPage() {
  const session = await requirePermission('transfer_student');
  const supabase = await createServerSupabaseClient();
  const [{ data: students }, { data: classes }, { data: streams }, { data: years }, { data: transferSchools }, { data: requests }] = await Promise.all([
    supabase.from('students').select('id, first_name, last_name, admission_number, class_id, stream_id, status, classes(name), streams(name)').eq('school_id', session.school!.id).eq('status', 'active').order('last_name'),
    supabase.from('classes').select('id, name').eq('school_id', session.school!.id).order('order_index').order('name'),
    supabase.from('streams').select('id, name, class_id').eq('school_id', session.school!.id).order('name'),
    supabase.from('academic_years').select('id, name, is_current').eq('school_id', session.school!.id).order('name', { ascending: false }),
    supabase.rpc('list_transfer_schools'),
    supabase.from('student_transfer_requests').select('id, source_school_id, target_school_id, source_student_id, target_student_id, student_snapshot, reason, status, requested_at').in('status', ['pending', 'accepted', 'rejected']).order('requested_at', { ascending: false }).limit(50),
  ]);
  const currentYear = (years ?? []).find((year: any) => year.is_current) ?? (years ?? [])[0];
  const schoolNameById = new Map((transferSchools ?? []).map((school: any) => [school.id, school.name]));
  const currentSchoolId = session.school!.id;

  return <main className="space-y-6">
    <header><h2 className="text-xl font-semibold text-ink">Student transfers and promotion</h2><p className="help-text mt-1">Promote learners at the end of an academic year, move them between classes, or process a controlled school transfer.</p></header>
    <Card><CardHeader><CardTitle>Promote a student</CardTitle></CardHeader><p className="help-text mb-4">Creates the academic-year placement and updates the current class without removing historical results.</p><div className="space-y-3">{(students ?? []).map((student: any) => <ActionForm key={student.id} action={promoteStudent} submitLabel="Promote" className="grid gap-3 border-b border-line pb-4 md:grid-cols-5"><input type="hidden" name="student_id" value={student.id} /><div className="text-sm"><p className="font-medium">{student.first_name} {student.last_name}</p><p className="help-text">{student.admission_number} · {student.classes?.name ?? 'Unassigned'}</p></div><Select name="academic_year_id" defaultValue={currentYear?.id ?? ''} required><option value="">Academic year</option>{(years ?? []).map((year: any) => <option key={year.id} value={year.id}>{year.name}{year.is_current ? ' (current)' : ''}</option>)}</Select><Select name="class_id" defaultValue="" required><option value="">Next class</option>{(classes ?? []).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select name="stream_id" defaultValue=""><option value="">No stream</option>{(streams ?? []).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></ActionForm>)}</div>{!(students ?? []).length && <p className="help-text">No active students are available for promotion.</p>}</Card>
    <Card><CardHeader><CardTitle>Move within this school</CardTitle></CardHeader><p className="help-text mb-4">Use this for a class or stream correction in the current academic year.</p><div className="space-y-3">{(students ?? []).map((student: any) => <ActionForm key={student.id} action={transferStudentWithinSchool} submitLabel="Move" className="grid gap-3 border-b border-line pb-4 md:grid-cols-4"><input type="hidden" name="student_id" value={student.id} /><div className="text-sm"><p className="font-medium">{student.first_name} {student.last_name}</p><p className="help-text">{student.admission_number} · {student.classes?.name ?? 'Unassigned'}</p></div><Select name="class_id" defaultValue={student.class_id ?? ''} required><option value="">Class</option>{(classes ?? []).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select name="stream_id" defaultValue={student.stream_id ?? ''}><option value="">No stream</option>{(streams ?? []).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></ActionForm>)}</div></Card>
    <Card><CardHeader><CardTitle>Request transfer to another school</CardTitle></CardHeader><p className="help-text mb-4">The destination school must accept the request before a new student record is created there. Source marks and history remain here.</p><div className="space-y-3">{(students ?? []).map((student: any) => <ActionForm key={student.id} action={requestSchoolTransfer} submitLabel="Request transfer" className="grid gap-3 border-b border-line pb-4 md:grid-cols-4"><input type="hidden" name="student_id" value={student.id} /><div className="text-sm"><p className="font-medium">{student.first_name} {student.last_name}</p><p className="help-text">{student.admission_number} · {student.classes?.name ?? 'Unassigned'}</p></div><Select name="target_school_id" defaultValue="" required><option value="">Destination school</option>{(transferSchools ?? []).map((school: any) => <option key={school.id} value={school.id}>{school.name}</option>)}</Select><Input name="reason" placeholder="Reason (optional)" /></ActionForm>)}</div>{!(transferSchools ?? []).length && <p className="help-text">No other active schools are available for transfer.</p>}</Card>
    <Card><CardHeader><CardTitle>Transfer requests</CardTitle></CardHeader>{(requests ?? []).length ? <div className="space-y-4">{(requests ?? []).map((request: any) => { const snapshot = request.student_snapshot as any; const isIncoming = request.target_school_id === currentSchoolId; return <div key={request.id} className="border-b border-line pb-4"><div className="flex flex-wrap justify-between gap-2 text-sm"><div><p className="font-medium">{snapshot?.first_name} {snapshot?.last_name} · {snapshot?.admission_number}</p><p className="help-text">{isIncoming ? `Incoming from ${schoolNameById.get(request.source_school_id) ?? 'another school'}` : `Outgoing to ${schoolNameById.get(request.target_school_id) ?? 'another school'}`} · {request.status}</p></div><p className="text-muted">{new Date(request.requested_at).toLocaleDateString()}</p></div>{isIncoming && request.status === 'pending' && <div className="mt-3 flex flex-wrap gap-3"><ActionForm action={acceptSchoolTransfer} submitLabel="Accept" className="flex flex-wrap items-end gap-2"><input type="hidden" name="request_id" value={request.id} /><Input name="admission_number" placeholder="New admission number" required /><Select name="class_id" defaultValue="" required><option value="">Assign class</option>{(classes ?? []).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select name="stream_id" defaultValue=""><option value="">No stream</option>{(streams ?? []).map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></ActionForm><ActionForm action={rejectSchoolTransfer} submitLabel="Reject"><input type="hidden" name="request_id" value={request.id} /></ActionForm></div>}{!isIncoming && request.status === 'pending' && <ActionForm action={cancelSchoolTransfer} submitLabel="Cancel"><input type="hidden" name="request_id" value={request.id} /></ActionForm>}</div>; })}</div> : <p className="help-text">No transfer requests recorded.</p>}</Card>
  </main>;
}
