import type { ModuleWorkspaceConfig } from '@/components/modules/module-workspace';

const schoolWorkspaces: Record<string, ModuleWorkspaceConfig> = {
  '/dashboard/students': {
    title: 'Students', description: 'Manage learner records, enrollment, transfers, and class placement from one workspace.', primaryAction: { label: 'Add student', href: '/dashboard/students/add' }, metrics: [{ label: 'Learners', value: '0', detail: 'No learner records yet' }, { label: 'New this term', value: '0', detail: 'Awaiting enrollment data' }, { label: 'Transfers', value: '0', detail: 'No pending transfers' }], sections: [{ title: 'All students', description: 'Search and review enrolled learners.', href: '/dashboard/students', action: 'Open student register' }, { title: 'Transfers', description: 'Review incoming and outgoing learner transfers.', href: '/dashboard/students/transfers', action: 'Review transfers' }],
  },
  '/dashboard/staff': {
    title: 'Staff', description: 'Organize staff records, positions, and access to the school workspace.', primaryAction: { label: 'Manage roles', href: '/dashboard/staff/roles' }, metrics: [{ label: 'Staff members', value: '0', detail: 'Staff register is ready' }, { label: 'Roles', value: '4', detail: 'Default roles created' }, { label: 'Permissions', value: 'Catalog', detail: 'Managed by administrators' }], sections: [{ title: 'Users', description: 'Review staff accounts and access.', href: '/dashboard/staff/users', action: 'Open users' }, { title: 'Roles & permissions', description: 'Configure what each role can do.', href: '/dashboard/staff/roles', action: 'Open role matrix' }],
  },
  '/dashboard/attendance': {
    title: 'Attendance', description: 'Record daily attendance and follow up on absences by class and staff member.', primaryAction: { label: 'Mark attendance', href: '/dashboard/attendance/class' }, metrics: [{ label: 'Today', value: '0%', detail: 'No attendance recorded' }, { label: 'Present', value: '0', detail: 'Awaiting today\'s register' }, { label: 'Absent', value: '0', detail: 'No absences recorded' }], sections: [{ title: 'Class attendance', description: 'Take today\'s register for a class.', href: '/dashboard/attendance/class', action: 'Take register' }, { title: 'History', description: 'Review attendance trends and previous registers.', href: '/dashboard/attendance/history', action: 'Open history' }],
  },
  '/dashboard/finance': {
    title: 'Finance', description: 'Set up fee structures, record payments, and monitor outstanding balances.', primaryAction: { label: 'Record payment', href: '/dashboard/finance/payments' }, metrics: [{ label: 'Collected', value: '0', detail: 'No payments recorded' }, { label: 'Outstanding', value: '0', detail: 'No fee balances yet' }, { label: 'Reports', value: '0', detail: 'No financial reports' }], sections: [{ title: 'Fee structures', description: 'Define what learners should pay.', href: '/dashboard/finance/fee-structures', action: 'Open fee structures' }, { title: 'Payments', description: 'Record and review received payments.', href: '/dashboard/finance/payments', action: 'Open payments' }],
  },
  '/dashboard/letters': {
    title: 'Letters & documents', description: 'Create reusable templates and generate school documents from structured records.', primaryAction: { label: 'Create template', href: '/dashboard/letters/templates' }, metrics: [{ label: 'Templates', value: '0', detail: 'No templates created' }, { label: 'Documents', value: '0', detail: 'No documents generated' }, { label: 'Certificates', value: '0', detail: 'No certificates generated' }], sections: [{ title: 'Templates', description: 'Build templates for letters and certificates.', href: '/dashboard/letters/templates', action: 'Open templates' }, { title: 'Generated documents', description: 'Find and download generated files.', href: '/dashboard/letters', action: 'Open documents' }],
  },
};

export function getSchoolWorkspace(href: string, label: string): ModuleWorkspaceConfig {
  return schoolWorkspaces[href] ?? {
    title: label, description: `Manage ${label.toLowerCase()} for your school from this workspace.`, metrics: [{ label: 'Records', value: '0', detail: 'No records yet' }, { label: 'This term', value: '0', detail: 'No activity yet' }, { label: 'Status', value: 'Ready', detail: 'Workspace available' }], sections: [{ title: label, description: 'Use this workspace to review and manage records for this area.', href, action: 'Open workspace' }],
  };
}

export function getPlatformWorkspace(href: string, label: string): ModuleWorkspaceConfig {
  const configs: Record<string, ModuleWorkspaceConfig> = {
    '/platform/analytics': { title: 'Platform analytics', description: 'Monitor school adoption, activity, and platform health.', metrics: [{ label: 'Schools', value: '0', detail: 'No school metrics loaded' }, { label: 'Active users', value: '0', detail: 'No activity recorded' }, { label: 'Health', value: 'Ready', detail: 'Platform services available' }], sections: [{ title: 'School activity', description: 'Review activity across registered schools.', href: '/platform/schools', action: 'Open schools' }, { title: 'System audit', description: 'Inspect platform-level events.', href: '/platform/audit', action: 'Open audit log' }] },
    '/platform/users': { title: 'Platform users', description: 'Review platform administrator access and support roles.', metrics: [{ label: 'Administrators', value: '0', detail: 'No platform users listed' }, { label: 'Support users', value: '0', detail: 'No support users listed' }, { label: 'Status', value: 'Ready', detail: 'Access control available' }], sections: [{ title: 'Access review', description: 'Platform user management is ready for administrator records.', href: '/platform/audit', action: 'Review audit activity' }] },
    '/platform/settings': { title: 'Platform settings', description: 'Configure platform-wide operational preferences and support defaults.', metrics: [{ label: 'Configuration', value: 'Ready', detail: 'Settings workspace available' }, { label: 'Changes', value: '0', detail: 'No changes recorded' }, { label: 'Audit', value: 'On', detail: 'Changes are tracked' }], sections: [{ title: 'System audit', description: 'Review configuration changes.', href: '/platform/audit', action: 'Open audit log' }] },
    '/platform/schools/register': { title: 'Register school', description: 'Use the school onboarding flow to create a new tenant workspace.', primaryAction: { label: 'Open registration', href: '/register' }, metrics: [{ label: 'Flow', value: 'Ready', detail: 'Registration is available' }, { label: 'Schools', value: '0', detail: 'No new school in this session' }, { label: 'Audit', value: 'On', detail: 'Registration is tracked' }], sections: [{ title: 'School onboarding', description: 'Create a school administrator account and workspace.', href: '/register', action: 'Start registration' }] },
  };
  return configs[href] ?? { title: label, description: `Manage ${label.toLowerCase()} from this platform workspace.`, metrics: [{ label: 'Records', value: '0', detail: 'No records yet' }, { label: 'Activity', value: '0', detail: 'No activity yet' }, { label: 'Status', value: 'Ready', detail: 'Workspace available' }], sections: [{ title: label, description: 'The workspace is ready for platform administration.', href: '/platform', action: 'Back to platform' }] };
}
