// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/[...slug]" | "/dashboard/attendance/approval" | "/dashboard/attendance/class" | "/dashboard/attendance/history" | "/dashboard/attendance/personal" | "/dashboard/exams" | "/dashboard/exams/class-results" | "/dashboard/exams/marks" | "/dashboard/exams/reports" | "/dashboard/exams/results" | "/dashboard/finance" | "/dashboard/finance/outstanding" | "/dashboard/notifications" | "/dashboard/settings/academics" | "/dashboard/settings/communication" | "/dashboard/settings/grading" | "/dashboard/settings/school" | "/dashboard/settings/system" | "/dashboard/setup" | "/dashboard/staff" | "/dashboard/staff/[id]/edit" | "/dashboard/staff/add" | "/dashboard/staff/audit" | "/dashboard/staff/permissions" | "/dashboard/staff/roles" | "/dashboard/students" | "/dashboard/students/[id]/edit" | "/dashboard/students/add" | "/dashboard/students/transfers" | "/dashboard/syllabus" | "/dashboard/syllabus/class" | "/dashboard/syllabus/subject" | "/dashboard/syllabus/topics" | "/dashboard/timetable" | "/dashboard/timetable/[id]" | "/dashboard/timetable/class" | "/dashboard/timetable/conflicts" | "/dashboard/timetable/manage" | "/dashboard/timetable/periods" | "/dashboard/timetable/published" | "/dashboard/timetable/room" | "/dashboard/timetable/rooms" | "/dashboard/timetable/rules" | "/dashboard/timetable/settings" | "/dashboard/timetable/teacher" | "/dashboard/timetable/weekly" | "/login" | "/platform" | "/platform/[...slug]" | "/platform/audit" | "/platform/schools" | "/register" | "/school-suspended"
type AppRouteHandlerRoutes = "/api/exams/reports/pdf" | "/api/timetable/export" | "/favicon.ico"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/platform"
type RedirectRoutes = "/dashboard/finance/fee-structures" | "/dashboard/finance/payments" | "/dashboard/finance/reports"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/exams/reports/pdf": {}
  "/api/timetable/export": {}
  "/dashboard": {}
  "/dashboard/[...slug]": { "slug": string[]; }
  "/dashboard/attendance/approval": {}
  "/dashboard/attendance/class": {}
  "/dashboard/attendance/history": {}
  "/dashboard/attendance/personal": {}
  "/dashboard/exams": {}
  "/dashboard/exams/class-results": {}
  "/dashboard/exams/marks": {}
  "/dashboard/exams/reports": {}
  "/dashboard/exams/results": {}
  "/dashboard/finance": {}
  "/dashboard/finance/fee-structures": {}
  "/dashboard/finance/outstanding": {}
  "/dashboard/finance/payments": {}
  "/dashboard/finance/reports": {}
  "/dashboard/notifications": {}
  "/dashboard/settings/academics": {}
  "/dashboard/settings/communication": {}
  "/dashboard/settings/grading": {}
  "/dashboard/settings/school": {}
  "/dashboard/settings/system": {}
  "/dashboard/setup": {}
  "/dashboard/staff": {}
  "/dashboard/staff/[id]/edit": { "id": string; }
  "/dashboard/staff/add": {}
  "/dashboard/staff/audit": {}
  "/dashboard/staff/permissions": {}
  "/dashboard/staff/roles": {}
  "/dashboard/students": {}
  "/dashboard/students/[id]/edit": { "id": string; }
  "/dashboard/students/add": {}
  "/dashboard/students/transfers": {}
  "/dashboard/syllabus": {}
  "/dashboard/syllabus/class": {}
  "/dashboard/syllabus/subject": {}
  "/dashboard/syllabus/topics": {}
  "/dashboard/timetable": {}
  "/dashboard/timetable/[id]": { "id": string; }
  "/dashboard/timetable/class": {}
  "/dashboard/timetable/conflicts": {}
  "/dashboard/timetable/manage": {}
  "/dashboard/timetable/periods": {}
  "/dashboard/timetable/published": {}
  "/dashboard/timetable/room": {}
  "/dashboard/timetable/rooms": {}
  "/dashboard/timetable/rules": {}
  "/dashboard/timetable/settings": {}
  "/dashboard/timetable/teacher": {}
  "/dashboard/timetable/weekly": {}
  "/favicon.ico": {}
  "/login": {}
  "/platform": {}
  "/platform/[...slug]": { "slug": string[]; }
  "/platform/audit": {}
  "/platform/schools": {}
  "/register": {}
  "/school-suspended": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/platform": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
