// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[...slug]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/attendance/approval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/attendance/approval">> = Specific
  const handler = {} as typeof import("../../app/dashboard/attendance/approval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/attendance/class/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/attendance/class">> = Specific
  const handler = {} as typeof import("../../app/dashboard/attendance/class/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/attendance/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/attendance/history">> = Specific
  const handler = {} as typeof import("../../app/dashboard/attendance/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/attendance/personal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/attendance/personal">> = Specific
  const handler = {} as typeof import("../../app/dashboard/attendance/personal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/exams/class-results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/exams/class-results">> = Specific
  const handler = {} as typeof import("../../app/dashboard/exams/class-results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/exams/marks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/exams/marks">> = Specific
  const handler = {} as typeof import("../../app/dashboard/exams/marks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/exams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/exams">> = Specific
  const handler = {} as typeof import("../../app/dashboard/exams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/exams/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/exams/reports">> = Specific
  const handler = {} as typeof import("../../app/dashboard/exams/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/exams/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/exams/results">> = Specific
  const handler = {} as typeof import("../../app/dashboard/exams/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/finance/outstanding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finance/outstanding">> = Specific
  const handler = {} as typeof import("../../app/dashboard/finance/outstanding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finance">> = Specific
  const handler = {} as typeof import("../../app/dashboard/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications">> = Specific
  const handler = {} as typeof import("../../app/dashboard/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/academics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/academics">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/academics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/communication/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/communication">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/communication/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/grading/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/grading">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/grading/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/school/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/school">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/school/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/system">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/setup">> = Specific
  const handler = {} as typeof import("../../app/dashboard/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/staff/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/staff/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/staff/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/staff/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/staff/add">> = Specific
  const handler = {} as typeof import("../../app/dashboard/staff/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/staff/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/staff/audit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/staff/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/staff">> = Specific
  const handler = {} as typeof import("../../app/dashboard/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/staff/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/staff/permissions">> = Specific
  const handler = {} as typeof import("../../app/dashboard/staff/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/staff/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/staff/roles">> = Specific
  const handler = {} as typeof import("../../app/dashboard/staff/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/students/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/students/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/students/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/students/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/students/add">> = Specific
  const handler = {} as typeof import("../../app/dashboard/students/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/students">> = Specific
  const handler = {} as typeof import("../../app/dashboard/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/students/transfers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/students/transfers">> = Specific
  const handler = {} as typeof import("../../app/dashboard/students/transfers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/syllabus/class/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/syllabus/class">> = Specific
  const handler = {} as typeof import("../../app/dashboard/syllabus/class/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/syllabus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/syllabus">> = Specific
  const handler = {} as typeof import("../../app/dashboard/syllabus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/syllabus/subject/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/syllabus/subject">> = Specific
  const handler = {} as typeof import("../../app/dashboard/syllabus/subject/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/syllabus/topics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/syllabus/topics">> = Specific
  const handler = {} as typeof import("../../app/dashboard/syllabus/topics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/class/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/class">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/class/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/conflicts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/conflicts">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/conflicts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/manage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/manage">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/manage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/periods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/periods">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/periods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/published/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/published">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/published/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/room/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/room">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/room/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/rooms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/rooms">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/rooms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/rules">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/teacher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/teacher">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/teacher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/timetable/weekly/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timetable/weekly">> = Specific
  const handler = {} as typeof import("../../app/dashboard/timetable/weekly/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[...slug]">> = Specific
  const handler = {} as typeof import("../../app/platform/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/audit">> = Specific
  const handler = {} as typeof import("../../app/platform/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform">> = Specific
  const handler = {} as typeof import("../../app/platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/schools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/schools">> = Specific
  const handler = {} as typeof import("../../app/platform/schools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/school-suspended/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/school-suspended">> = Specific
  const handler = {} as typeof import("../../app/school-suspended/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exams/reports/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exams/reports/pdf">> = Specific
  const handler = {} as typeof import("../../app/api/exams/reports/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/timetable/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/timetable/export">> = Specific
  const handler = {} as typeof import("../../app/api/timetable/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/favicon.ico/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/favicon.ico">> = Specific
  const handler = {} as typeof import("../../app/favicon.ico/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/platform">> = Specific
  const handler = {} as typeof import("../../app/platform/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
